language: smalltalk
sudo: false
os:
- linux
smalltalk:
- Pharo64-7.0
- Pharo-7.0
- Pharo-6.1
- Pharo-6.0
- Pharo-5.0
matrix:
  allow_failures:
  - smalltalk: Pharo64-7.0
  - smalltalk: Pharo-7.0
  fast_finish: true
before_deploy:
  - cp "${SMALLTALK_CI_IMAGE}" "Willow-JQueryUI.image"
  - cp "${SMALLTALK_CI_CHANGES}" "Willow-JQueryUI.changes"
  - zip -q "${TRAVIS_BRANCH}-${TRAVIS_SMALLTALK_VERSION}.zip" "Willow-JQueryUI.image" "Willow-JQueryUI.changes"
deploy:
  provider: releases
  api_key:
    secure: HpPIvRo7q67ujd+CIK2CPbc0JJwTpRZjH6C4SK8EsRJMtU666vtOKnlg7I9/ioD343hXoiAXiJp2ulWHxqZy5LOd8fdrgbBx1dme3h7QqVn5dTCIIRVJfiwJsHymiJxefmeb4fg0SNpUaQAlPoifUrkX92f4tXRpIL4UHOPYAo1fhrnLaSxxkZto8KZHg9PYEJ2xaj2SfU1J1Ov8AJiBoI6umamC345bLJXkniUix92XIEnirNpUlGHzFg4MbQAElA9xd5uKCfan9+BNVsVN6gDFRALEymlonPq53GVqnQqw4kEYWR3R43cI2x5kCxDxoCUmoXHoUEgyA4KDoekko3SGrgjjbO/Fl5nhzPpZz3NhkVJei1YojUJT/RvP+bSe+4rW1AMLjitwxYiYI2cFXpToAhXODb+dVT/IGB5BdMPKok3k4P58QfQLxNFCSZVpLSd1do/lS/AqSzhPr8s6zbpA8ucYjAEzJqw+zuqUYpIyZoDRtCILqmgGjCegrdU0YuP2SBY0ZWdAAcdmxVqWLpPTmismX02w+WS8Y9dXt6WGsRYZSgHLLktGilEW+p8/THA5qD1GHwYBxXaYjOiBGJCAm128JJiceJBQrR948Zev/zn3hgKydlTbLVDP+vd0Uf1FpNlKJWUQaC5K9WbdszgrZ2v+HYd/f+g/4xMGaWQ=
  file: "${TRAVIS_BRANCH}-${TRAVIS_SMALLTALK_VERSION}.zip"
  skip_cleanup: true
  on:
    repo: ba-st/Willow-JQueryUI
    tags: true
