Extension { #name : #ComponentClassificationCommandBuilder }

{ #category : #'*Willow-JQueryUI' }
ComponentClassificationCommandBuilder >> jQueryUI [

	classificationNamespace := classificationNamespace >> #jQueryUI
]

{ #category : #'*Willow-JQueryUI' }
ComponentClassificationCommandBuilder >> uiButton [

	^ self commandStyledWith: #uiButton
]

{ #category : #'*Willow-JQueryUI' }
ComponentClassificationCommandBuilder >> uiButtonIconPrimary [

	^ self commandStyledWith: #uiButtonIconPrimary
]

{ #category : #'*Willow-JQueryUI' }
ComponentClassificationCommandBuilder >> uiCornerAll [

	^ self commandStyledWith: #uiCornerAll
]

{ #category : #'*Willow-JQueryUI' }
ComponentClassificationCommandBuilder >> uiCornerLeft [

	^ self commandStyledWith: #uiCornerLeft
]

{ #category : #'*Willow-JQueryUI' }
ComponentClassificationCommandBuilder >> uiHelperClearfix [

	^ self commandStyledWith: #uiHelperClearfix
]

{ #category : #'*Willow-JQueryUI' }
ComponentClassificationCommandBuilder >> uiIcon [

	^ self commandStyledWith: #uiIcon
]

{ #category : #'*Willow-JQueryUI' }
ComponentClassificationCommandBuilder >> uiIconClose [

	^ self commandStyledWith: #uiIconClose
]

{ #category : #'*Willow-JQueryUI' }
ComponentClassificationCommandBuilder >> uiIconMinusthick [

	^ self commandStyledWith: #uiIconMinusthick
]

{ #category : #'*Willow-JQueryUI' }
ComponentClassificationCommandBuilder >> uiIconPlusthick [

	^ self commandStyledWith: #uiIconPlusthick
]

{ #category : #'*Willow-JQueryUI' }
ComponentClassificationCommandBuilder >> uiStateDefault [

	^ self commandStyledWith: #uiStateDefault
]

{ #category : #'*Willow-JQueryUI' }
ComponentClassificationCommandBuilder >> uiStateHighlight [

	^ self commandStyledWith: #uiStateHighlight
]

{ #category : #'*Willow-JQueryUI' }
ComponentClassificationCommandBuilder >> uiWidget [

	^ self commandStyledWith: #uiWidget
]

{ #category : #'*Willow-JQueryUI' }
ComponentClassificationCommandBuilder >> uiWidgetContent [

	^ self commandStyledWith: #uiWidgetContent
]

{ #category : #'*Willow-JQueryUI' }
ComponentClassificationCommandBuilder >> uiWidgetHeader [

	^ self commandStyledWith: #uiWidgetHeader
]
