"
A collection of css classes on the class side for JQueryUI
"
Class {
	#name : #JQueryUICssStyles,
	#superclass : #Object,
	#category : 'Willow-JQueryUI-WebViews'
}

{ #category : #jQueryUI }
JQueryUICssStyles class >> uiButton [

	^'ui-button'
]

{ #category : #jQueryUI }
JQueryUICssStyles class >> uiButtonIconPrimary [

	^ 'ui-button-icon-primary'
]

{ #category : #jQueryUI }
JQueryUICssStyles class >> uiCornerAll [

	^'ui-corner-all'
]

{ #category : #jQueryUI }
JQueryUICssStyles class >> uiCornerLeft [

	^'ui-corner-left'
]

{ #category : #dialog }
JQueryUICssStyles class >> uiDialog [

	^'ui-dialog'
]

{ #category : #dialog }
JQueryUICssStyles class >> uiDialogButtonset [

	^'ui-dialog-buttonset'
]

{ #category : #dialog }
JQueryUICssStyles class >> uiDialogContent [

	^'ui-dialog-content'
]

{ #category : #jQueryUI }
JQueryUICssStyles class >> uiFront [

	^'ui-front'
]

{ #category : #jQueryUI }
JQueryUICssStyles class >> uiHelperClearfix [

	^'ui-helper-clearfix'
]

{ #category : #jQueryUI }
JQueryUICssStyles class >> uiIcon [

	^'ui-icon'
]

{ #category : #icons }
JQueryUICssStyles class >> uiIconArrowthick1E [

	^'ui-icon-arrowthick-1-e'
]

{ #category : #icons }
JQueryUICssStyles class >> uiIconArrowthick1S [

	^'ui-icon-arrowthick-1-s'
]

{ #category : #icons }
JQueryUICssStyles class >> uiIconArrowthick1W [

	^'ui-icon-arrowthick-1-w'
]

{ #category : #icons }
JQueryUICssStyles class >> uiIconCancel [

	^'ui-icon-cancel'
]

{ #category : #icons }
JQueryUICssStyles class >> uiIconCheck [

	^'ui-icon-check'
]

{ #category : #icons }
JQueryUICssStyles class >> uiIconClose [

	^'ui-icon-close'
]

{ #category : #icons }
JQueryUICssStyles class >> uiIconClosethick [

	^'ui-icon-closethick'
]

{ #category : #icons }
JQueryUICssStyles class >> uiIconComment [

	^'ui-icon-comment'
]

{ #category : #icons }
JQueryUICssStyles class >> uiIconMinusthick [

	^'ui-icon-minusthick'
]

{ #category : #icons }
JQueryUICssStyles class >> uiIconPencil [

	^'ui-icon-pencil'
]

{ #category : #icons }
JQueryUICssStyles class >> uiIconPlus [

	^'ui-icon-plus'
]

{ #category : #icons }
JQueryUICssStyles class >> uiIconPlusthick [

	^'ui-icon-plusthick'
]

{ #category : #icons }
JQueryUICssStyles class >> uiIconSeekNext [

	^'ui-icon-seek-next'
]

{ #category : #icons }
JQueryUICssStyles class >> uiIconSeekPrev [

	^'ui-icon-seek-prev'
]

{ #category : #icons }
JQueryUICssStyles class >> uiIconStar [

	^'ui-icon-star'
]

{ #category : #jQueryUI }
JQueryUICssStyles class >> uiStateDefault [

	^'ui-state-default'
]

{ #category : #jQueryUI }
JQueryUICssStyles class >> uiStateFocus [

	^'ui-state-focus'
]

{ #category : #jQueryUI }
JQueryUICssStyles class >> uiStateHighlight [

	^'ui-state-highlight'
]

{ #category : #jQueryUI }
JQueryUICssStyles class >> uiStateHover [

	^'ui-state-hover'
]

{ #category : #jQueryUI }
JQueryUICssStyles class >> uiWidget [

	^'ui-widget'
]

{ #category : #jQueryUI }
JQueryUICssStyles class >> uiWidgetContent [

	^'ui-widget-content'
]

{ #category : #jQueryUI }
JQueryUICssStyles class >> uiWidgetHeader [

	^'ui-widget-header'
]
